name: FUEL_CI_Common

on:
  workflow_call:
    inputs:
      RELEASE_VERSION:
        required: false
        type: string
      DEV_DIR:
        required: false
        type: string
      RELEASES_DIR:
        required: false
        type: string
        default: ./public/releases 

env:
  ONTO_DIR: src
  ONTO_FILE: fuel.ttl
  ONTO_ABBREV: fuel
  DOCS_DIR: docs
  RELEASES_DIR: releases

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DEV_DIR: ${{ inputs.DEV_DIR || 'dev' }}
      RELEASE_VERSION: ${{ inputs.RELEASE_VERSION || '' }}
      GIST_ID: ${{ secrets.GIST_ID || '' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Java Setup
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Install ROBOT
        run: |
          wget -q https://github.com/ontodev/robot/releases/download/v1.9.8/robot.jar -O robot.jar
          curl -sL https://raw.githubusercontent.com/ontodev/robot/master/bin/robot > robot
          chmod +x robot

      - name: Install Python packages
        run: |
          python -m pip install --upgrade pip
          pip install rdflib dotenv pylode

      - name: Validate ontology profile
        id: profile
        run: |
          ./robot validate-profile --input "${ONTO_DIR}/${ONTO_FILE}" --profile DL -vvv || \
          (echo "Profile check failed." && exit 1)

      - name: Badge — Syntax
        if: always()
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: ${{ env.GIST_ID }}
          filename: fuel-ci-profile-${{ github.ref_name }}.json
          label: OWL DL Profile (${{ github.ref_name }})
          message: ${{ steps.profile.outcome }}
          color: ${{ steps.profile.outcome == 'success' && 'brightgreen' || steps.profile.outcome == 'cancelled' && 'yellow' || 'red' }}

      - name: Reasoning and consistency check
        id: reasoning
        run: |
          if ./robot reason --reasoner HermiT --input "${ONTO_DIR}/${ONTO_FILE}" --output reasoned.owl; then
            echo "result=consistent" >> $GITHUB_OUTPUT
          else
            echo "result=inconsistent" >> $GITHUB_OUTPUT
            exit 1
          fi
 
      - name: Badge — Reasoning
        if: always()
        uses: schneegans/dynamic-badges-action@v1.7.0
        with:
          auth: ${{ secrets.GIST_TOKEN }}
          gistID: ${{ env.GIST_ID }}
          filename: ontology-ci-reasoning-${{ github.ref_name }}.json
          label: Reasoning (${{ github.ref_name }})
          message: ${{ steps.reasoning.outputs.result }}
          color: ${{ steps.reasoning.outputs.result == 'consistent' && 'brightgreen' || 'red' }}

      - name: Generate ontology syntaxes and documentation              
        run: |
            python3 src/scripts/onto_syntax_doc.py

      - name: Upload dev artifact
        if: ${{ inputs.DEV_DIR != '' && inputs.DEV_DIR != null }}
        uses: actions/upload-artifact@v4
        with:
          name: dev
          path: ${{ inputs.DEV_DIR }}