name: FUEL_CI_Dev

on:
  push:
    branches:      
      - dev      

jobs:
  dev:
    uses: ./.github/workflows/ci-common.yaml
    with:
      DEV_DIR: ./public/dev   # build ontologies into "dev" folder

  deploy:
    needs: dev
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download dev artifact
        uses: actions/download-artifact@v4
        with:
          name: dev
          path: ./public/dev

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload dev site artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./public

      - name: Deploy dev site
        id: deployment
        uses: actions/deploy-pages@v4.0.5