name: FUEL_CI_Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (e.g., 1.0.0)'
        required: true

  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    uses: ./.github/workflows/ci-common.yaml
    with:
      RELEASE_VERSION: ${{ github.event.inputs.release_version }}

  deploy:
    needs: release
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5