name: FUEL_CI_Release

on:
  workflow_dispatch:
    inputs:
      release_version:
        description: 'Release version (e.g., 1.0.0)'
        required: true

  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    uses: ./.github/workflows/ci-common.yaml
    with:
      RELEASE_VERSION: ${{ github.event.inputs.release_version }}
      RELEASES_DIR: ./public/releases

  deploy:
    needs: release
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download release artifact
        uses: actions/download-artifact@v4
        with:
          name: release
          path: ./public/releases   # download into ./public/releases

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
      
      - name: Upload site artifact
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./public           # publish the full public/ tree
      
      - name: Deploy site
        id: deployment
        uses: actions/deploy-pages@v4