
name: FUEL CI
on:
  workflow_dispatch:

jobs:
  build:
    env:
      ONTO_FILE: fuel.ttl
      ONTO_ABBREV: fuel
      DOCS_DIR: docs
    
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4
  
    - name: Java Setup
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: '17'
    
    - name: Install ROBOT
      run: |
        wget -q https://github.com/ontodev/robot/releases/download/v1.9.8/robot.jar -O robot.jar
        curl -sL https://raw.githubusercontent.com/ontodev/robot/master/bin/robot > robot
        chmod +x robot
    
    - name: Install RDFLib/PyLode/DotEnv
      run: |
            python -m pip install --upgrade pip
            pip install rdflib dotenv pylode

    - name: Validate ontology profile
      id: profile
      run: |
        # If parsing fails, this step will exit non-zero
        ./robot validate-profile --input "$ONTO_FILE" --profile DL|| \
        (echo "Profile check failed." && exit 1)
  
    - name: Reasoning and consistency check (HermiT)
      id: reason
      run: |
       ./robot reason --reasoner HermiT --input "$ONTO_FILE" --output reasoned.owl \
        > reason.stdout 2> reason.stderr \
        && echo "REASON_RESULT=consistent" >> $GITHUB_ENV \
        || echo "REASON_RESULT=inconstent" >> $GITHUB_ENV

    - name: Generate documentation with Pylode
      id: pylode
      run: |
          mkdir -p "$DOCS_DIR/docs/pylode/"
          pylode -o "$DOCS_DIR/docs/pylode/index" \
            "$ONTO_FILE"  

    - name: Configure Pages
      uses: actions/configure-pages@v5            

    - name: Upload Pages artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ env.DOCS_DIR }}
 
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4